# Generated by Django 3.1.7 on 2021-02-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210324_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dealine',
            new_name='deadline',
        ),
    ]
